name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull cwlumm/employee_manager:latest
      - name: Delete Old Docker Container
        run: docker rm -f employee_manager-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8000:8000 --name employee_manager-container cwlumm/employee_manager -e ${{secrets.MONGO_URL}}
