name: CI Pipeline

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: |
          docker build -t employee_manager --build-arg MONGO_URL="${{secrets.MONGO_URL}}" .
          docker tag employee_manager:latest cwlumm/employee_manager:latest
      - name: Push to Dockerhub
        run: docker push cwlumm/employee_manager:latest
